plugins:
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-paginate

exclude:
  - "/vendor/"

# Site settings
title: .NET Notts - Blog
#subtitle: "A simple yet classy theme for your Jekyll website or blog"
name: .NET Notts
description:  >
  The Blog of the .NET Notts Meetup
baseurl: "" 
url: "" 
cover: "/assets/header-image.png"
logo: "/assets/logo.png"

# Build settings
markdown: kramdown
paginate: 10
paginate_path: "/page:num/"
inter_post_navigation: false
highlightjs_theme: "monokai-sublime"

# Archive settings (see https://github.com/jekyll/jekyll-archives/)
jekyll-archives:
  enabled:
    - categories
    - tags
  layout: 'archive'
  permalinks:
    category: '/category/:name/'
    tag: '/tag/:name/'

# Google analytics
ga_tracking_id: "UA-130637122-2"

# Category descriptions (for archive pages)
descriptions:
  - cat: jekyll
    desc: "Posts describing Jekyll setup techniques."

# Social
social:
  - name: Twitter
    icon: twitter
    username: dotnetnotts
    url: https://twitter.com/dotnetnotts
    desc: Follow us on Twitter
    share: true

  - name: GitHub
    icon: github
    username: dotnetnotts
    url: https://github.com/dotnetnotts/dotnetnotts-blog
    desc: Fork us on GitHub
    share: false

  - name: LinkedIn
    icon: linkedin
    username: .NET Notts
    url: https://www.linkedin.com/company/dotnet-notts/
    desc: Connect with us on LinkedIn
    share: true

protocols:
    twitter_image: "/assets/logo.png"
permalink: /:year/:month/:day/:title:output_ext